/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor from "../../src/plugins/strapi-plugin-ckeditor/strapi-admin";
import contentVersioning from "@notum-cz/strapi-plugin-content-versioning/strapi-admin";
import dragDropContentTypes from "@retikolo/drag-drop-content-types/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiAdvancedUuid from "strapi-advanced-uuid/strapi-admin";
import contentTypeExplorer from "strapi-content-type-explorer/strapi-admin";
import strapiPhoneValidator from "strapi-phone-validator/strapi-admin";
import comments from "strapi-plugin-comments/strapi-admin";
import duplicateButton from "strapi-plugin-duplicate-button/strapi-admin";
import importExportEntries from "strapi-plugin-import-export-entries/strapi-admin";
import menus from "strapi-plugin-menus/strapi-admin";
import softDelete from "strapi-plugin-soft-delete/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    ckeditor: ckeditor,
    "content-versioning": contentVersioning,
    "drag-drop-content-types": dragDropContentTypes,
    "strapi-cloud": strapiCloud,
    "color-picker": colorPicker,
    documentation: documentation,
    graphql: graphql,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    "strapi-advanced-uuid": strapiAdvancedUuid,
    "content-type-explorer": contentTypeExplorer,
    "strapi-phone-validator": strapiPhoneValidator,
    comments: comments,
    "duplicate-button": duplicateButton,
    "import-export-entries": importExportEntries,
    menus: menus,
    "soft-delete": softDelete,
  },
});
